apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: kubetrial-admin
      containers:
      - name: backend
        image: ghcr.io/natrongmbh/kubetrial-backend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
          - name: CORS
            value: "*"
        envFrom:
          - secretRef:
              name: kubetrial-secrets
        ports:
        - containerPort: 8000
          name: http
      initContainers:
        - name: pg-isready
          image: postgres
          command:
          - 'sh'
          - '-c'
          - |
            until pg_isready -h postgresql.kubetrial.svc.cluster.local -p 5432; do
              echo "Waiting for PostgreSQL to be ready..."
              sleep 2
            done
          - 'echo'
          - 'PostgreSQL is ready'
