apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: kubetrial-admin
      containers:
      - name: backend
        image: ghcr.io/natrongmbh/kubetrial-backend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
          - name: CORS
            value: "*"
        envFrom:
          - secretRef:
              name: kubetrial-secrets
        ports:
        - containerPort: 8000
          name: http
