apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/natrongmbh/kubetrial-frontend:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
          - name: ENV_API_URI
            value: "" # requried
        ports:
        - containerPort: 3000
          name: http
      initContainers:
        - name: pg-isready
          image: postgres
          command: 
          - 'sh'
          - '-c'
          - |
            until pg_isready -h postgresql.kubetrial.svc.cluster.local -p 5432; do
              echo "Waiting for PostgreSQL to be ready..."
              sleep 2
            done
          - 'echo'
          - 'PostgreSQL is ready'