apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/natrongmbh/kubetrial-frontend:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
          - name: ENV_API_URI
            value: "" # requried
        ports:
        - containerPort: 3000
          name: http